-- instance (Error e) => Monad (Either e) where
--   return x = Right x
--   Right x >>= f = f x
--   Left err >>= f = Left err
--   fail msg = Left (strMsg msg)

-- Left "Boom" >>= \x -> return (x+1)
-- Left "Boom"
-- Right 100 >>= \x -> return (x+1)
-- Right 101
-- Right 100 >>= \x -> Left "no way!"
-- Left "No way!"